language: ruby
rvm: 2.2.0
script: "bin/rake spec"
before_install:
  - "echo 'deb http://ppa.launchpad.net/chromium-daily/stable/ubuntu precise main' | sudo tee -a /etc/apt/sources.list >/dev/null"
  - "echo 'deb-src http://ppa.launchpad.net/chromium-daily/stable/ubuntu precise main' | sudo tee -a /etc/apt/sources.list >/dev/null"
  - "sudo apt-get install chromium-browser=47.0.2526.73-0"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - sleep 3 # give xvfb time to start
