language: ruby
rvm: 2.2.0
script: "bin/rake spec"
before_script:
  - "echo ${GEM_HOME}/gems | xargs ls"
  - "printenv"
  - "echo ${GEM_HOME}/gems/chromedriver-helper-1.0.0/bin/chromedriver-update | xargs bundle exec ruby"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - sleep 3 # give xvfb time to start
