language: ruby
rvm: 2.2.0
script: "bin/rake spec"
before_install:
  - "echo 'deb https://launchpad.net/ubuntu/+source/chromium-browser/ trusty universe' | sudo tee -a /etc/apt/sources.list >/dev/null"
  - "echo 'deb-src https://launchpad.net/ubuntu/+source/chromium-browser/ trusty universe' | sudo tee -a /etc/apt/sources.list >/dev/null"
  - "sudo apt-get install chromium-browser=47.0.2526.73-0ubuntu0.14.04.1.1106"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - sleep 3 # give xvfb time to start
